version: 0.0
os: linux
files:
  - source: release.zip
    destination: /home/ec2-user/myapp
permissions:
  - object: /home/ec2-user/myapp
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: deployment/stop_app.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: deployment/install_deps.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: deployment/start_app.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: deployment/validate.sh
      timeout: 60
      runas: ec2-user
